language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install httpretty --use-mirrors"
  - "pip install coveralls"
script: 
  - "coverage run --source=TwitterSearch setup.py test"
after_success:
  coveralls
branches:
  only:
    - master
    - devel
